### PR TITLE
multinom_tidiers

### PR DESCRIPTION
**Pull request by nutterb**
Adds tidiers for multinomial logistic regression using the nnet package

If your'e interested in having something for multinomial logistic regression, I think this captures the results and follows the format you've used throughout the package fairly well.  

The output for a regression with a three category response looks like:
```
  y.level        term     estimate  std.error  statistic      p.value
1       4 (Intercept) 1.435319e-05  5.3170471 -2.0973180 3.596544e-02
2       4         mpg 1.027312e-08 67.9313211 -0.2707696 7.865683e-01
3       4 factor(am)1 1.690352e+00  0.2680456  1.9583870 5.018462e-02
4       5 (Intercept) 1.442327e+00  0.2924021  1.2525833 2.103574e-01
5       5         mpg 1.473333e+05 66.8958481  0.1778952 8.588053e-01
6       5 factor(am)1 5.578072e+09  2.1699437 10.3422543 4.537363e-25
```

If you have a different vision of how this should look, I'm happy to work on that too.

### CODE REVIEW

**Comment by dgrtwo** [comment]
Sorry for the delay. Great work!!

**Comment by nutterb** [comment]
You were at some big event when I pushed this, and then I forgot all about it. What a happy surprise

**Comment by dgrtwo** [comment]
Also: if you would like to provide your name and/or email I could add you to DESCRIPTION as a contributor.

**Comment by nutterb** [comment]
You can use Benjamin Nutter with nutter@battelle.org. it's generous of you to offer for such a small contribution (And I won't be hurt to be left off the list given it was so small)

**Comment by dgrtwo** [comment]
Not at all. Added

**Pull request merged**
